# Generated by Django 5.2.15 on 2026-06-12 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipID', models.CharField(max_length=20, unique=True)),
                ('equipName', models.CharField(max_length=200)),
                ('equipDesc', models.CharField(blank=True, default='', max_length=200)),
                ('quantTotal', models.IntegerField()),
                ('quantAvail', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkedOutAt', models.DateTimeField(auto_now_add=True)),
                ('returnedAt', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='authentication.employee')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='equipment.equipment')),
            ],
        ),
    ]
